#!/usr/bin/env python3
"""Deterministic level-data generator for Color Clash.

Produces game/data/levels.json. This is a design-time authoring tool, not
part of the shipped game — levels are consumed at runtime purely as data
(see game/scripts/levels/level_database.gd). Re-run after editing the
CURVE below to regenerate the campaign.

Usage: python3 tools/level_gen/generate_levels.py
"""
import json
import os

ALL_COLORS = ["red", "blue", "yellow", "green", "purple"]
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "game", "data", "levels.json")


def obstacles_for(level_id, width, height):
    obs = []
    # Teach obstacles gradually: none -> ice -> lock -> stone -> mixed.
    if level_id < 4:
        return obs
    if level_id < 8:
        count = min(3, (level_id - 3))
        for i in range(count):
            obs.append({"type": "ice", "x": 2 + i, "y": 1, "hp": 2})
    elif level_id < 12:
        count = min(3, (level_id - 7))
        for i in range(count):
            obs.append({"type": "lock", "x": 1 + i, "y": height - 2, "hp": 1})
    elif level_id < 16:
        count = min(3, (level_id - 11))
        for i in range(count):
            obs.append({"type": "stone", "x": 3 + i, "y": 2})
    else:
        # Mixed obstacle levels for the later campaign.
        obs.append({"type": "ice", "x": 1, "y": 1, "hp": 2})
        obs.append({"type": "lock", "x": width - 2, "y": height - 2, "hp": 1})
        obs.append({"type": "stone", "x": width // 2, "y": height // 2})
    return obs


def objectives_for(level_id, colors, width, height):
    cycle = level_id % 5
    base_target = 12 + level_id
    if cycle == 0:
        return [{"type": "clear_color", "color": colors[0], "target": base_target}]
    if cycle == 1:
        return [{"type": "reach_score", "target": 4000 + level_id * 500}]
    if cycle == 2:
        return [{"type": "create_powers", "power": "any", "target": min(2 + level_id // 4, 8)}]
    if cycle == 3:
        obs_types = [o["type"] for o in obstacles_for(level_id, width, height)]
        if obs_types:
            return [{"type": "break_obstacles", "obstacle": "any", "target": len(obs_types)}]
        return [{"type": "reach_score", "target": 4500 + level_id * 400}]
    # Mixed objective.
    return [
        {"type": "clear_color", "color": colors[0], "target": base_target},
        {"type": "clear_color", "color": colors[1], "target": max(8, base_target - 6)},
    ]


def build_level(level_id):
    width = 7 + min(level_id // 6, 2)       # 7 -> 9
    height = 8 + min(level_id // 5, 3)      # 8 -> 11
    color_count = 3 if level_id < 3 else (4 if level_id < 10 else 5)
    colors = ALL_COLORS[:color_count]
    move_limit = max(14, 24 - level_id // 2)
    difficulty = "easy" if level_id < 5 else ("medium" if level_id < 14 else "hard")
    obstacles = obstacles_for(level_id, width, height)
    objectives = objectives_for(level_id, colors, width, height)
    reward_coins = 80 + level_id * 15

    return {
        "id": level_id,
        "name": "Level %d" % level_id,
        "width": width,
        "height": height,
        "colors": colors,
        "move_limit": move_limit,
        "objectives": objectives,
        "obstacles": obstacles,
        "reward": {"coins": reward_coins},
        "difficulty": difficulty,
    }


def main():
    levels = [build_level(i) for i in range(1, 26)]
    payload = {
        "_comment": "Generated by tools/level_gen/generate_levels.py. Edit the generator, not this file, for bulk changes.",
        "levels": levels,
    }
    out_path = os.path.abspath(OUT_PATH)
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")
    print("Wrote %d levels to %s" % (len(levels), out_path))


if __name__ == "__main__":
    main()
